IF NOT EXISTS(SELECT * FROM sys.databases WHERE name = 'BoilerplateDb')
  BEGIN
    CREATE DATABASE [BoilerplateDb]
  END
GO

USE [BoilerplateDb]
GO

DROP TABLE IF EXISTS [dbo].[UserToken]

DROP TABLE IF EXISTS [dbo].[User]

CREATE TABLE [dbo].[User](
	[Id] BIGINT IDENTITY(1,1) NOT NULL,
	[Username] VARCHAR(50),
	[Email] VARCHAR(50),
	[PasswordHash] VARCHAR(100),
	[IsAdmin] BIT NOT NULL DEFAULT 0,
	[IsDeleted] BIT NOT NULL DEFAULT 0
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[UserToken](
	[UserId] [bigint] NOT NULL,
	[Token] [nvarchar](850) NOT NULL,
	[DeviceId] [nvarchar](100) NOT NULL,
	[IsActive] [bit] NOT NULL,
	[ExpiryDate] [datetime] NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ModifiedDate] [datetime] NULL,
	CONSTRAINT FK_UserToken_User FOREIGN KEY (UserId)
	REFERENCES [dbo].[User] (Id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
	CONSTRAINT [PK_UserToken] PRIMARY KEY CLUSTERED 
(
	[CreatedDate] DESC,
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Token] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[UserToken] ADD  DEFAULT (getdate()) FOR [CreatedDate]
GO

INSERT INTO [dbo].[User] (Username, Email, PasswordHash, IsAdmin, IsDeleted) VALUES
('guest', 'guest@guest.co', 'guest', 1, 0),
('minch', 'bminchinton0@blogspot.com', 'qsk3', 1, 0),
('cecca', 'ceccersley1@state.tx.us', 'Mnh12', 0, 0),
('jollo', 'jollarenshaw2@4shared.com', 'd4a6', 1, 0),
('amucklow3', 'bpresdee3@shareasale.com', 'PBgtMngboo', 0, 1),
('pknoble4', 'tphippen4@ovh.net', '6xP3wqvX1', 1, 0),
('cdayton5', 'cbarthorpe5@dmoz.org', 'SopMcKn', 1, 0),
('scouronne6', 'arichardot6@oakley.com', 'xI0dGLqVpwy', 1, 1),
('kconn7', 'vyellowlee7@pcworld.com', 'ElghjKYocji', 1, 0),
('rcalvie8', 'sgraundisson8@tinyurl.com', 'qqQoWD1zr5Em', 1, 0),
('cnewsham9', 'tloveman9@ca.gov', 'GxWNn7', 1, 0),
('mmccaugheya', 'dmccandiea@narod.ru', 'k8oUSKCQG87', 1, 0),
('iwilkinsb', 'cmcinteerb@blogs.com', 'Wv1AVnZw', 0, 1),
('nschoolcroftc', 'rkanwellc@wikispaces.com', '1coUVN', 0, 1),
('iheintschd', 'dcloughtond@dmoz.org', 'imaLRMyiw', 0, 1),
('rkubistae', 'manselme@walmart.com', 'VwYmiFFbe', 0, 0),
('juccellif', 'mpickworthf@accuweather.com', 'xRVfnIObm', 0, 0),
('beymerg', 'csucklingg@washington.edu', 'pTEtRV588V', 1, 0),
('sandreassonh', 'enuscheh@biglobe.ne.jp', 'FFSsG60xj2', 1, 1),
('challsi', 'mmcsporrini@elpais.com', 'SPJvwFnZ', 0, 1),
('asantarellij', 'nkockj@hatena.ne.jp', 'Q5p2n2Yeha', 1, 0),
('afurmedgek', 'tmillek@dion.ne.jp', 'g4CIPyIMuT14', 0, 1),
('lsterryl', 'parmingerl@imdb.com', 'jur7wn19Ik5', 1, 1),
('ngogartym', 'spicoppm@google.com.br', 'tBBBQF', 0, 1),
('kghiroldin', 'mwinchcombn@i2i.jp', 'i1hSoCstpG', 1, 1),
('rpuzeyo', 'rjayso@unblog.fr', 'KYNKbWH0S', 1, 1),
('gferrarinip', 'vkordtp@marketwatch.com', 'o7W0pyRP0suy', 1, 1),
('kscothorneq', 'sfarnieq@comsenz.com', 'GENFBY53O', 1, 0),
('jkinforthr', 'iiwanickir@umn.edu', 'UiTks943Dldx', 0, 1),
('dmilroys', 'mladsons@hibu.com', 'P74BwgNNv6E6', 1, 1),
('hmabbet', 'vrenshallt@quantcast.com', 'cCRIgnjfRa', 0, 0),
('lstubbsu', 'ecammisu@pcworld.com', 'p56zNvDDNdfC', 1, 1),
('ccurseyv', 'nrodsonv@uol.com.br', 'w4QJ8h833vE', 0, 1),
('dcoburnw', 'rbriddenw@zdnet.com', 'tZQfpDG6In', 0, 1),
('nnaylorx', 'bkitcatx@simplemachines.org', 'NrgyhLse5XNe', 0, 0),
('spahly', 'jemsdeny@theatlantic.com', 'sgXkNY', 0, 1),
('gsmurfittz', 'vmorcombez@alibaba.com', 'HNN0FehNNKN', 1, 1),
('dfrantzen10', 'jhamp10@vistaprint.com', 'HocyKSiVN9A', 1, 1),
('mmclean11', 'athickpenny11@seesaa.net', '3V5Oe5', 1, 1),
('gstreight12', 'rcoulthard12@dyndns.org', 'tQf50G', 1, 1),
('umatyushkin13', 'criach13@newsvine.com', 'avDHwetNb8f', 1, 1),
('aplatt14', 'oseckom14@alexa.com', 'rqN81nEN', 1, 0),
('nmicheu15', 'srawe15@go.com', 'tYX474', 0, 0),
('tgheorghescu16', 'rritmeyer16@nsw.gov.au', 'kPxGKrA6', 0, 1),
('firnys17', 'trustan17@latimes.com', 'eGMUp80G9Wi', 1, 1),
('twigfield18', 'mwoltering18@admin.ch', 'xCVIFAzKtq', 1, 1),
('sreucastle19', 'tcaroli19@altervista.org', 'zVVIAUP416MJ', 0, 1),
('ealenichicov1a', 'tkitteridge1a@state.gov', 'iW7GpKkrPICn', 0, 0),
('tfurmston1b', 'kpoulgreen1b@canalblog.com', 'DRyh1rrRHZc', 1, 0),
('hdolan1c', 'rcaven1c@jugem.jp', 'pR2Llo', 0, 1),
('dheard1d', 'wlittrell1d@example.com', 'a0IBb9A3X', 1, 0),
('fozanne1e', 'bspringall1e@usatoday.com', 'h09mnUQda', 0, 0),
('eleney1f', 'rmckellen1f@chron.com', 'XXW6qMRq', 1, 0),
('jbleything1g', 'mdonaghy1g@godaddy.com', 't61JmJp0', 1, 1),
('dhearsum1h', 'hclewley1h@artisteer.com', 'UpaoEUlvwS', 1, 1),
('peager1i', 'omcdougall1i@shinystat.com', 'h4eDFbP', 0, 1),
('sgaiger1j', 'ewitcher1j@zimbio.com', 'go3xJU', 0, 0),
('nmoorcraft1k', 'phanmer1k@virginia.edu', 'tDRKrHZGL8Qv', 0, 1),
('bdurning1l', 'bborg1l@dmoz.org', 'MabzZ0kSpc', 0, 1),
('lmckinie1m', 'dtadman1m@drupal.org', 'HyaZqWuS1u', 0, 0),
('ohaseley1n', 'rhanmore1n@princeton.edu', 'geO4aTUbXi3', 0, 1),
('rskingley1o', 'lvasilyonok1o@ameblo.jp', 'jBLugTCpi', 0, 0),
('nrillett1p', 'rshawley1p@tiny.cc', 'oAKvS9Ksh', 1, 0),
('vgrandham1q', 'gpapen1q@yale.edu', 'vwo8cw2', 0, 1),
('dgalloway1r', 'mwhiffin1r@g.co', 'xxDQKmEhMB9f', 1, 0),
('ischole1s', 'hchafer1s@pen.io', 'IkmNCMnMWW7', 1, 0),
('bastlatt1t', 'acreebo1t@plala.or.jp', '2SzlNj', 1, 0),
('mcuredell1u', 'bchipman1u@narod.ru', '1BWWBks27', 0, 0),
('ehorley1v', 'mstrover1v@sakura.ne.jp', 'H8scsQ99uiri', 0, 1),
('hkelston1w', 'mhowitt1w@cloudflare.com', 'UVTufP7R', 0, 0),
('jbavester1x', 'lmcgaugan1x@storify.com', 'Blh3ZFbIAofC', 1, 0),
('cfleckness1y', 'bmcbain1y@google.it', 'gW9GhZa', 0, 0),
('mbowfin1z', 'fskarin1z@netvibes.com', 'cJHLZt', 1, 0),
('sdionsetto20', 'hberrill20@slideshare.net', '5vaKa15ZnRF', 0, 1),
('alempertz21', 'cperl21@mozilla.org', 'b77AVf', 0, 1),
('cgaule22', 'elaverty22@ca.gov', 'YXgHWpem', 1, 1),
('crubinov23', 'ntudhope23@cargocollective.com', 'cb7hYd', 0, 0),
('kchillingworth24', 'adelacourt24@berkeley.edu', 'O5x1hDJe44', 0, 1),
('torhrt25', 'jzamora25@godaddy.com', 'i1zleYXtkvKi', 0, 0),
('ctrehearne26', 'pmcmeekan26@un.org', 'K5n1u4f', 0, 1),
('mcarus27', 'ecatherick27@ucsd.edu', 'EXqkMrU', 1, 0),
('cfaragher28', 'ehousden28@nifty.com', '7O3rLLJ', 0, 0),
('wkeefe29', 'bcutford29@fc2.com', 'TjTM90wmlMeq', 0, 1),
('hree2a', 'llambourne2a@i2i.jp', 'UeHl7exh3qM5', 1, 1),
('rserot2b', 'kwestpfel2b@census.gov', 'xo5h9jKGP', 1, 1),
('gmassinger2c', 'cwaterstone2c@nba.com', 'NqVx9LD', 1, 0),
('operrycost2d', 'mstarsmeare2d@spiegel.de', 'Cdo9OtDc2Zw', 0, 0),
('shurley2e', 'bguerrier2e@dedecms.com', '8skjF4i', 0, 0),
('mpollicott2f', 'kluno2f@mtv.com', 'lyDZbqLBZ', 0, 0),
('acrisford2g', 'lshawcross2g@soup.io', 'TBesY7x2U', 0, 0),
('lloyns2h', 'calleburton2h@dyndns.org', 'qwh6sk9', 1, 1),
('pnuttall2i', 'kskylett2i@sina.com.cn', 'UysVkD6FRvd', 0, 1),
('astack2j', 'dchampken2j@ovh.net', 'I6PL4y', 0, 0),
('inevison2k', 'streweela2k@homestead.com', 'I9GGEdWT3a', 1, 1),
('agrabert2l', 'cgiraldo2l@cmu.edu', 'WS6op37SS9W', 0, 1),
('ethom2m', 'gmeo2m@cdbaby.com', 'rgIMSyqzDKLu', 1, 1),
('cferreres2n', 'kreichert2n@lulu.com', 'm6DRdmDZxI', 0, 1),
('dbilam2o', 'braun2o@psu.edu', 'wVLQSQF9D5q', 0, 0),
('slevis2p', 'eadhams2p@a8.net', 'FyHHnHp', 1, 1),
('gblackston2q', 'eyegorev2q@sina.com.cn', 'GstIIxB97', 0, 0),
('nrushford2r', 'tdwight2r@cbslocal.com', 'JatmbRqENfWV', 0, 1),
('cfaucherand2s', 'lcurston2s@so-net.ne.jp', 'TIj4k4j4E7NN', 1, 0),
('agooddie2t', 'hkingstne2t@cloudflare.com', 'reg3XAWgZzt', 1, 0),
('eevanson2u', 'grawdales2u@loc.gov', 'vOK6SQC5DsD', 0, 0),
('silyinykh2v', 'glunge2v@economist.com', '9EIl3CkiVe', 1, 1),
('yhaimes2w', 'rdran2w@skyrock.com', 'lhOKtVjclYA', 1, 1),
('bswindall2x', 'mdhooge2x@wp.com', 'ULKe9C0Y5w', 1, 0),
('edelieu2y', 'peaglen2y@ameblo.jp', 'X9iqeXBa', 1, 0),
('ohubbis2z', 'bhelleckas2z@wordpress.com', 'DyufHT', 1, 1),
('tnewlands30', 'acamilletti30@scribd.com', 'Kte6ccfs', 0, 0),
('dcoop31', 'dbolles31@aol.com', 'wFBtxDY', 1, 1),
('tandriolli32', 'poruane32@wp.com', '6N7II0OKsb8', 1, 0),
('leagles33', 'emacguigan33@de.vu', 'wnuhBna4k', 1, 0),
('gmcclurg34', 'edampier34@github.com', 'tOXdxQkh', 1, 0),
('kskocroft35', 'odella35@china.com.cn', 'Ik42HVKB', 0, 1),
('rrapport36', 'pbolus36@seattletimes.com', 'XYg3pKRf', 1, 0),
('ckann37', 'gbeckey37@unblog.fr', 'iIGK4UD', 0, 0),
('btathacott38', 'gglassopp38@sun.com', 'DVbD8C8', 0, 0),
('lbarthrop39', 'dmengue39@smugmug.com', 'Cmyxq5cTf', 0, 1),
('wmacellen3a', 'hwemes3a@twitter.com', 'TEs78SRjznGr', 0, 0),
('aortiga3b', 'imellhuish3b@pbs.org', 'jaDAoy', 1, 0),
('ascrauniage3c', 'iolder3c@auda.org.au', 'oLeaCSm', 0, 1),
('adaunter3d', 'dbenduhn3d@sun.com', 'GlOofh', 0, 0),
('hwiburn3e', 'nmoylan3e@furl.net', '0QMfCUFmMZdx', 1, 0),
('cjager3f', 'rordidge3f@opera.com', '93V5ECD6XuP', 1, 1),
('qanderl3g', 'jrubinsaft3g@oracle.com', 'X1pDWNtf7', 1, 1),
('mfeaviour3h', 'rhanselmann3h@cargocollective.com', '2g4TPmaW', 1, 1),
('msteely3i', 'fdonnellan3i@hhs.gov', 'e9DdhyS3oEDL', 1, 1),
('dlamprey3j', 'dbanane3j@eepurl.com', 'sg4aKf', 1, 1),
('mchittock3k', 'unobbs3k@geocities.com', '2IvDCY5wCW', 1, 1),
('ejohnston3l', 'cfalcus3l@rambler.ru', 'JDYMo4vEexg', 1, 0),
('mscolland3m', 'nolivetta3m@1und1.de', 'kFtFVA9', 0, 0),
('askain3n', 'nrye3n@hao123.com', 'xXdUf9Kh', 1, 1),
('smcconway3o', 'lprys3o@themeforest.net', '0NDFac6j7Sen', 0, 1),
('ryesenin3p', 'blacrouts3p@rakuten.co.jp', 'AahpMkPN2lx', 0, 0),
('pcowderoy3q', 'plerwill3q@blogger.com', 'tBiBqt9', 0, 1),
('k13r', 'eomond3r@multiply.com', 'HWTlnIOAWmvj', 1, 1),
('mmacparland3s', 'jpretorius3s@istockphoto.com', 'aisNSUSMy', 0, 0),
('kbletso3t', 'wofficer3t@icq.com', 'pgC6n6fG', 1, 1),
('aroony3u', 'elowater3u@state.gov', 'pkorVi2P', 1, 0),
('tpenkethman3v', 'nswadlinge3v@hao123.com', 'yDOitxLTT', 1, 1),
('khoffner3w', 'mdenrico3w@dion.ne.jp', 'FvPdQKBd4Ztf', 0, 1),
('cgreggs3x', 'fbillingham3x@shinystat.com', 'Xms6riEO53s', 1, 1),
('fslemming3y', 'rcundict3y@naver.com', 'FgUd1AKFHIm', 1, 1),
('jinkle3z', 'hashbrook3z@bluehost.com', 'PS62lH9ce', 1, 0),
('achristmas40', 'gdumbrall40@360.cn', '1k30PqyrHE', 1, 1),
('cshildrick41', 'abullivant41@woothemes.com', '7IzEkng6H', 1, 1),
('alocard42', 'hmengo42@slate.com', 'ybvAbmkeyQ', 1, 1),
('kholbarrow43', 'olarraway43@cdbaby.com', 'hFQXAG', 0, 0),
('etarbard44', 'glatan44@kickstarter.com', 'USdbkHSt14', 0, 0),
('fhowland45', 'alovat45@spotify.com', 'SH4LDEWO', 0, 1),
('aabrahamovitz46', 'freichelt46@webs.com', 'y0hSiSb', 0, 0),
('ireilly47', 'ogundrey47@seesaa.net', 'N9g4OVIiEAGc', 1, 1),
('amuglestone48', 'tsimonot48@storify.com', 'Sn9YTP', 0, 1),
('tseleway49', 'byellep49@vk.com', 'Q6l4V9Augey', 1, 1),
('mhartzogs4a', 'vdruett4a@dagondesign.com', 'HdoTimB', 0, 1),
('cdurak4b', 'bgourley4b@thetimes.co.uk', 'aHJaXiYym', 1, 0),
('cjay4c', 'bdevaux4c@google.com', 'slkTXN', 0, 1),
('lfenge4d', 'cbrimfield4d@squarespace.com', 'Q5UZzbQFFV', 0, 1),
('mromanet4e', 'lboadby4e@yahoo.co.jp', 'criuDAxAa4JT', 0, 0),
('ptanby4f', 'rscain4f@g.co', 'Le9wlXVLzejQ', 1, 1),
('jskiplorne4g', 'bmeakin4g@nba.com', '7k7P7VxD5', 1, 1),
('mbeak4h', 'lgarms4h@shutterfly.com', 'a7fYDF8VY5s5', 0, 1),
('spashen4i', 'adumphreys4i@squidoo.com', 'tMVz6eIKUkN0', 0, 0),
('rpendrey4j', 'gduberry4j@friendfeed.com', 'TpZnssPn', 0, 1),
('dfogel4k', 'lhancell4k@angelfire.com', 'Scv4bo', 1, 1),
('kjarnell4l', 'cetchells4l@cocolog-nifty.com', 'gYnODJzc2Ihz', 0, 0),
('bvalek4m', 'gyoodall4m@omniture.com', 'Cfg2hP7', 0, 1),
('brewcastle4n', 'warias4n@constantcontact.com', '5HRwYXT', 0, 1),
('mgothard4o', 'dmordue4o@msu.edu', '0FBGiC5pR0U', 1, 1),
('mbohin4p', 'hewings4p@seesaa.net', 'Am4cnrqmD', 1, 0),
('tsanbrooke4q', 'cpimbley4q@is.gd', 'vlfkfA', 0, 1),
('mceller4r', 'tkrinks4r@aol.com', 'tmsl2ja6', 1, 0),
('aordemann4s', 'velwin4s@usgs.gov', 'oAblTk5Vys', 0, 0),
('eteather4t', 'hsymones4t@mysql.com', 'fABY1STb', 0, 1),
('jantonucci4u', 'spimblotte4u@fema.gov', 'vZaGQV6JWi', 0, 1),
('cpyner4v', 'hcuthill4v@google.com.br', 'ibqOnew1', 0, 0),
('tdanat4w', 'msummerscales4w@wordpress.org', 'q0mZaDC', 0, 1),
('bcuree4x', 'nbricksey4x@reference.com', '9OTaqs', 0, 1),
('iabbey4y', 'bmossop4y@usgs.gov', 'ifyhpbSI', 1, 1),
('rwinfield4z', 'ftopling4z@creativecommons.org', '9xSkwye', 0, 0),
('beckford50', 'blernihan50@oakley.com', 'OqDz1Dat19', 1, 0),
('cmorford51', 'iodowne51@51.la', 'cSCj2w', 1, 0),
('jabbay52', 'mokinneally52@desdev.cn', 'p5LsOA', 0, 0),
('rmanjin53', 'rstudders53@sun.com', '6BxnLwY', 0, 1),
('gtelega54', 'ejammet54@mysql.com', 'zGbmAzhcA', 1, 1),
('lmenichillo55', 'khurleston55@de.vu', '9Ps3MS', 0, 1),
('ncardenosa56', 'rborgesio56@163.com', 'tbYNyPX', 1, 0),
('ttravers57', 'gbentjens57@pen.io', 'jFBAnvTi', 1, 1),
('akarpinski58', 'iplumbley58@plala.or.jp', '9FLOACnV', 0, 0),
('lreightley59', 'jeldred59@pcworld.com', 'aIPHwbw', 0, 1),
('tgosson5a', 'vsoldan5a@booking.com', 'YGSvPjDw27A', 0, 0),
('gglanton5b', 'hyushankin5b@utexas.edu', 'zw9h2fY11aC', 1, 0),
('weverson5c', 'clangthorn5c@apache.org', 'FLIvvHnKNp', 0, 0),
('rwither5d', 'adioniso5d@wikipedia.org', '0zlNNKZg', 1, 0),
('gboldra5e', 'cbulfoy5e@flavors.me', '4wyX04JC3', 1, 1),
('asamwayes5f', 'aantoniutti5f@amazon.co.jp', 'RqYv3O', 0, 1),
('eferrone5g', 'pleadbitter5g@columbia.edu', 'LfOvJrlUL', 1, 0),
('pgribbon5h', 'cwallsam5h@statcounter.com', 'bSfbi1', 0, 0),
('gmansel5i', 'dnoweak5i@sohu.com', 'sMI8Ndsm0', 1, 0),
('coxtaby5j', 'nkerslake5j@nationalgeographic.com', 'DqljAXaNSf', 1, 1);
